/**
 * Staging-table helpers for COPY loads: create a temp table mirroring the
 * target, then drop NOT NULL on columns we are not loading so COPY works.
 *
 * @module db/copy/staging
 */
import type { PoolClient } from 'pg';
import { quoteIdentifier, assertSafeIdentifiers } from '../identifiers.js';
import { getTableColumns } from './columns.js';

/** Fresh temp-table name for one COPY run (generated, never user input). */
export function tempTableName(tableName: string): string {
  return `temp_${tableName}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * Create staging table with an explicit name (generated by the caller).
 * Must run inside a transaction (temp table lives until commit).
 * Returns the validated column set of the target table.
 */
export async function createStagingTable(
  client: { query: PoolClient['query'] },
  tableName: string,
  stagingName: string,
  columns: string[],
): Promise<Set<string>> {
  await client.query(
    `CREATE TEMP TABLE ${stagingName} (LIKE ${tableName} INCLUDING DEFAULTS) ON COMMIT DROP`,
  );
  const validColSet = await getTableColumns(tableName);
  assertSafeIdentifiers('columns', columns, validColSet);
  const missingCols = [...validColSet].filter((c: string) => !columns.includes(c));
  for (const col of missingCols) {
    await client.query(
      `ALTER TABLE ${stagingName} ALTER COLUMN ${quoteIdentifier(col)} DROP NOT NULL`,
    );
  }
  return validColSet;
}
